# Changes here will be overwritten by Copier
_commit: 0.0.0
_src_path: gh:sphinx-contrib/copier-sphinxcontrib
author_email: firstname.lastname@domain.io
author_first_name: Firstname
author_last_name: Lastname
creation_year: "2024"
github_repo_name: sphinxcontrib-skeleton
github_user: username
project_name: Skeleton
project_slug: skeleton
short_description: An automatic build of the @sphinx-contrib/copier-sphinxcontrib copier template
